export const data = [
  {
    id: 1,
    name: "Erraid Mohamed",
    profession: "Teacher",
    email: "nm_djemai@esi.dz",
    phoneNumber: "0776262511",
    role: "Admin",
  },
  {
    id: 2,
    name: "Erraid Mohamed",
    profession: "Security",
    email: "nm_djemai@esi.dz",
    phoneNumber: "0776262511",
    role: "Technician",
  },
  {
    id: 3,
    name: "Erraid Mohamed",
    profession: "Student",
    email: "nm_djemai@esi.dz",
    phoneNumber: "0776262511",
    role: "Personal",
  },
  {
    id: 4,
    name: "Erraid Mohamed",
    profession: "Cleaning",
    email: "nm_djemai@esi.dz",
    phoneNumber: "0776262511",
    role: "Personal",
  },
  {
    id: 5,
    name: "Erraid Mohamed",
    profession: "Office Equipment Technician",
    email: "nm_djemai@esi.dz",
    phoneNumber: "0776262511",
    role: "Admin",
  },
  {
    id: 6,
    name: "Erraid Mohamed",
    profession: "Student",
    email: "nm_djemai@esi.dz",
    phoneNumber: "0776262511",
    role: "Personal",
  },
  {
    id: 7,
    name: "Erraid Mohamed",
    profession: "Network Technician",
    email: "nm_djemai@esi.dz",
    phoneNumber: "0776262511",
    role: "Technician",
  },
  {
    id: 8,
    name: "Erraid Mohamed",
    profession: "Mechanical Technician",
    email: "nm_djemai@esi.dz",
    phoneNumber: "0776262511",
    role: "Technician",
  },
  {
    id: 9,
    name: "Erraid Mohamed",
    profession: "Nm_djemai@Esi.Dz",
    email: "nm_djemai@esi.dz",
    phoneNumber: "0776262511",
    role: "Personal",
  },
  {
    id: 10,
    name: "Erraid Mohamed",
    profession: "Teacher",
    email: "nm_djemai@esi.dz",
    phoneNumber: "0776262511",
    role: "Admin",
  },
]

export default data
